import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { colors } from '../theme/colors';
import Card from '../components/Card';
import GoldButton from '../components/GoldButton';
import { supabase } from '../lib/supabase';
import { generateAIWorkout } from '../lib/aiGoals';

function formatRest(seconds) {
  if (!seconds) return '';
  if (seconds >= 60) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return s > 0 ? `${m}m ${s}s rest` : `${m}m rest`;
  }
  return `${seconds}s rest`;
}

export default function AIWorkoutScreen({ navigation }) {
  const [subscriptionTier, setSubscriptionTier] = useState(null);
  const [userId, setUserId] = useState(null);
  const [loading, setLoading] = useState(false);
  const [workout, setWorkout] = useState(null);
  const [checkingTier, setCheckingTier] = useState(true);

  useEffect(() => {
    (async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      setUserId(user.id);
      const { data: prof } = await supabase
        .from('profiles')
        .select('subscription_tier')
        .eq('id', user.id)
        .single();
      setSubscriptionTier(prof?.subscription_tier || 'free');
      setCheckingTier(false);
    })();
  }, []);

  const handleGenerate = async () => {
    if (!userId) return;
    setLoading(true);
    setWorkout(null);
    try {
      const result = await generateAIWorkout(userId);
      if (result) {
        setWorkout(result);
      } else {
        Alert.alert('Error', 'Could not generate workout. Please try again.');
      }
    } catch (err) {
      Alert.alert('Error', 'Something went wrong generating your workout.');
    }
    setLoading(false);
  };

  const handleLoadWorkout = () => {
    if (!workout) return;
    // Navigate to Workout tab with pre-filled data
    navigation.navigate('Main', {
      screen: 'Workout',
      params: { aiWorkout: workout },
    });
  };

  if (checkingTier) {
    return (
      <View style={styles.center}>
        <ActivityIndicator color={colors.gold} size="large" />
      </View>
    );
  }

  // FREE tier — locked screen
  if (subscriptionTier !== 'pro') {
    return (
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        <Card style={styles.lockedCard}>
          <Text style={styles.lockEmoji}>🔒</Text>
          <Text style={styles.lockedTitle}>AI Workout Generation</Text>
          <Text style={styles.lockedSubtitle}>Pro Feature</Text>
          <Text style={styles.lockedDesc}>
            Get a personalized workout generated by AI based on your training history, fitness level, and goals. 
            Progressive overload built in. No guesswork.
          </Text>
          <View style={styles.featureList}>
            {[
              '⚡ Adapts to your recent training',
              '📈 Applies progressive overload',
              '🎯 Matches your fitness goals',
              '🔄 Regenerate for variety',
            ].map((f) => (
              <Text key={f} style={styles.featureItem}>{f}</Text>
            ))}
          </View>
          <GoldButton
            title="UPGRADE TO PRO"
            onPress={() =>
              Alert.alert(
                'Upgrade to Pro',
                'Contact support or visit app settings to upgrade your subscription.',
                [{ text: 'OK' }]
              )
            }
            style={styles.upgradeBtn}
          />
        </Card>
      </ScrollView>
    );
  }

  // PRO tier
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerIcon}>⚛</Text>
        <Text style={styles.headerTitle}>AI COACH</Text>
      </View>

      {/* Generate button */}
      {!loading && (
        <GoldButton
          title={workout ? '🔄 REGENERATE' : '⚡ GENERATE WORKOUT'}
          onPress={handleGenerate}
          style={styles.generateBtn}
        />
      )}

      {/* Loading state */}
      {loading && (
        <Card style={styles.loadingCard}>
          <ActivityIndicator color={colors.gold} size="large" style={{ marginBottom: 12 }} />
          <Text style={styles.loadingText}>Analyzing your training history...</Text>
          <Text style={styles.loadingSubText}>Building personalized workout</Text>
        </Card>
      )}

      {/* Generated workout card */}
      {workout && !loading && (
        <Card style={styles.workoutCard}>
          {/* Header info */}
          <View style={styles.workoutHeader}>
            <View style={{ flex: 1 }}>
              <Text style={styles.workoutName}>{workout.workout_name}</Text>
              <Text style={styles.workoutFocus}>{workout.focus}</Text>
            </View>
            <View style={styles.durationBadge}>
              <Text style={styles.durationText}>{workout.estimated_duration_minutes}min</Text>
            </View>
          </View>

          {/* AI Notes */}
          {workout.ai_notes ? (
            <Text style={styles.aiNotes}>💬 {workout.ai_notes}</Text>
          ) : null}

          {/* Exercise list */}
          <Text style={styles.exercisesLabel}>EXERCISES</Text>
          {(workout.exercises || []).map((ex, idx) => (
            <View key={idx} style={styles.exerciseRow}>
              <View style={styles.exerciseIndexBox}>
                <Text style={styles.exerciseIndex}>{idx + 1}</Text>
              </View>
              <View style={{ flex: 1 }}>
                <Text style={styles.exerciseName}>{ex.name}</Text>
                <View style={styles.exerciseMeta}>
                  <Text style={styles.exerciseSetsReps}>
                    {ex.sets} sets × {ex.reps} reps
                    {ex.weight_lbs > 0 ? ` @ ${ex.weight_lbs} lbs` : ''}
                  </Text>
                  {ex.rest_seconds ? (
                    <Text style={styles.exerciseRest}>{formatRest(ex.rest_seconds)}</Text>
                  ) : null}
                </View>
                {ex.notes ? <Text style={styles.exerciseNotes}>{ex.notes}</Text> : null}
              </View>
            </View>
          ))}

          {/* Actions */}
          <GoldButton
            title="💪 LOAD INTO WORKOUT"
            onPress={handleLoadWorkout}
            style={styles.loadBtn}
          />
          <TouchableOpacity style={styles.regenBtn} onPress={handleGenerate}>
            <Text style={styles.regenBtnText}>🔄 REGENERATE</Text>
          </TouchableOpacity>
        </Card>
      )}

      {/* Empty state */}
      {!workout && !loading && (
        <Card style={styles.emptyCard}>
          <Text style={styles.emptyEmoji}>🤖</Text>
          <Text style={styles.emptyTitle}>Your AI Coach is Ready</Text>
          <Text style={styles.emptyDesc}>
            Tap Generate to get a personalized workout built around your training history and goals.
          </Text>
        </Card>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 48 },
  center: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 24,
    marginTop: 8,
  },
  headerIcon: { fontSize: 28, color: colors.gold },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.gold,
    letterSpacing: 3,
  },
  generateBtn: { marginBottom: 20 },
  loadingCard: { alignItems: 'center', paddingVertical: 32 },
  loadingText: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 4 },
  loadingSubText: { fontSize: 13, color: colors.muted },
  workoutCard: { marginBottom: 16 },
  workoutHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  workoutName: { fontSize: 20, fontWeight: '800', color: colors.text, marginBottom: 4 },
  workoutFocus: { fontSize: 13, color: colors.muted, textTransform: 'uppercase', letterSpacing: 0.5 },
  durationBadge: {
    backgroundColor: 'rgba(201,168,76,0.12)',
    borderWidth: 1,
    borderColor: colors.gold,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  durationText: { fontSize: 13, fontWeight: '700', color: colors.gold },
  aiNotes: {
    fontSize: 13,
    color: colors.muted,
    fontStyle: 'italic',
    marginBottom: 14,
    lineHeight: 18,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
    padding: 10,
  },
  exercisesLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.gold,
    letterSpacing: 2,
    marginBottom: 10,
    marginTop: 4,
  },
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border + '55',
  },
  exerciseIndexBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  exerciseIndex: { fontSize: 12, fontWeight: '700', color: colors.muted },
  exerciseName: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: 3 },
  exerciseMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  exerciseSetsReps: { fontSize: 12, color: colors.gold, fontWeight: '600' },
  exerciseRest: { fontSize: 12, color: colors.muted },
  exerciseNotes: { fontSize: 11, color: colors.muted, fontStyle: 'italic', marginTop: 3 },
  loadBtn: { marginTop: 20, marginBottom: 10 },
  regenBtn: {
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  regenBtnText: { fontSize: 13, color: colors.muted, fontWeight: '600' },
  // Free tier locked card
  lockedCard: { alignItems: 'center', padding: 24, marginTop: 20 },
  lockEmoji: { fontSize: 48, marginBottom: 12 },
  lockedTitle: { fontSize: 20, fontWeight: '800', color: colors.text, marginBottom: 4, textAlign: 'center' },
  lockedSubtitle: { fontSize: 12, color: colors.gold, fontWeight: '700', letterSpacing: 2, marginBottom: 16 },
  lockedDesc: { fontSize: 14, color: colors.muted, textAlign: 'center', lineHeight: 20, marginBottom: 20 },
  featureList: { alignSelf: 'stretch', marginBottom: 24, gap: 8 },
  featureItem: { fontSize: 14, color: colors.text },
  upgradeBtn: { alignSelf: 'stretch' },
  // Empty state
  emptyCard: { alignItems: 'center', paddingVertical: 40 },
  emptyEmoji: { fontSize: 48, marginBottom: 12 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 8 },
  emptyDesc: { fontSize: 13, color: colors.muted, textAlign: 'center', lineHeight: 18 },
});
